import type { AppData } from "./types";

export const PROGRAM_NAMES = [
  { name: "التهيئة والإرشاد", icon: "Compass" },
  { name: "التوجيه المهني", icon: "Briefcase" },
  { name: "رفق", icon: "HeartHandshake" },
  { name: "المهارات النفسية", icon: "Brain" },
  { name: "تنمية الدافعية للتعلم", icon: "Rocket" },
  { name: "السلوك الإيجابي", icon: "Smile" },
  { name: "الانضباط المدرسي", icon: "ShieldCheck" },
  { name: "الاستخدام الآمن للإنترنت", icon: "Globe" },
  { name: "دعم الحالات الخاصة", icon: "LifeBuoy" },
] as const;

export const STUDENT_CATEGORIES = [
  "الموهوبات",
  "المتفوقات",
  "كثيرات الغياب",
  "التأخر",
  "الضعيفات",
  "الظروف الخاصة",
  "الأيتام",
] as const;

export const SERVICE_TYPES = [
  "مجلس أولياء الأمور",
  "جلسة فردية",
  "جلسة جمعية",
  "إرشاد جمعي",
  "اجتماع اللجنة",
  "اجتماع المجلس الطلابي",
  "المواقف الطارئة",
] as const;

export const DAYS = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"] as const;

export function createSeedData(): AppData {
  return {
    counselor: {
      name: "أ. نورة بنت عبدالله القحطاني",
      jobNumber: "١٠٤٥٢٣٧",
      school: "المتوسطة الثانية عشرة",
      educationAdministration: "إدارة تعليم الرياض",
      stage: "المرحلة المتوسطة",
      academicYear: "١٤٤٧ هـ",
      term: "الفصل الدراسي الأول",
      email: "noura.counselor@moe.edu.sa",
      phone: "٠٥٥٤٤٣٣٢٢١",
      qualification: "بكالوريوس علم نفس - ماجستير إرشاد تربوي",
      experienceYears: "١٢ سنة",
    },
    programs: [
      {
        id: "p1",
        name: "التهيئة والإرشاد",
        icon: "Compass",
        goal: "تهيئة الطالبات المستجدات للبيئة المدرسية وتعريفهن بالأنظمة",
        targetGroup: "طالبات الصف الأول المتوسط",
        date: "2026-09-07",
        duration: "أسبوعان",
        beneficiaries: 120,
        place: "قاعة النشاط",
        owner: "المرشدة الطلابية",
        description:
          "برنامج تعريفي يشمل جولة مدرسية ولقاء تعريفي بالأنظمة واللوائح وخدمات التوجيه الطلابي.",
        activities: "لقاء تعريفي، جولة مدرسية، نشرة إرشادية، ركن تعريفي",
        attachments: "نشرة التهيئة.pdf",
        progress: 100,
        notes: "تفاعل ممتاز من الطالبات",
        results: "انخفاض شكاوى المستجدات، يوصى بتكرار البرنامج بداية كل عام",
        status: "منفذ",
      },
      {
        id: "p2",
        name: "التوجيه المهني",
        icon: "Briefcase",
        goal: "تعريف الطالبات بالمسارات الدراسية والمهن المستقبلية",
        targetGroup: "طالبات الصف الثالث المتوسط",
        date: "2026-10-12",
        duration: "أربعة أسابيع",
        beneficiaries: 85,
        place: "معمل الحاسب",
        owner: "المرشدة الطلابية بمشاركة معلمة الحاسب",
        description: "ورش تعريفية بالمسارات الثانوية ومقاييس الميول المهنية.",
        activities: "مقياس الميول، ورشة المسارات، لقاء مع مختصات",
        attachments: "عرض المسارات.pptx",
        progress: 60,
        notes: "بحاجة لتوسيع عدد الورش",
        results: "وعي أعلى بالمسارات لدى الطالبات",
        status: "قيد التنفيذ",
      },
      {
        id: "p3",
        name: "رفق",
        icon: "HeartHandshake",
        goal: "نشر ثقافة الرفق والحد من العنف داخل المدرسة",
        targetGroup: "جميع الطالبات",
        date: "2026-11-02",
        duration: "أسبوع",
        beneficiaries: 310,
        place: "الساحة المدرسية",
        owner: "لجنة التوجيه الطلابي",
        description: "فعاليات إذاعية وورش توعوية حول الرفق والتعامل الإيجابي.",
        activities: "إذاعة مدرسية، مسابقة، ركن الرفق",
        attachments: "",
        progress: 25,
        notes: "",
        results: "",
        status: "مخطط",
      },
      {
        id: "p4",
        name: "المهارات النفسية",
        icon: "Brain",
        goal: "تنمية مهارات إدارة الضغوط والقلق لدى الطالبات",
        targetGroup: "طالبات الصف الثاني والثالث",
        date: "2026-10-20",
        duration: "ثلاثة أسابيع",
        beneficiaries: 96,
        place: "غرفة التوجيه",
        owner: "المرشدة الطلابية",
        description: "جلسات جماعية لتعلم التنفس العميق وإدارة الوقت وضبط القلق.",
        activities: "جلسات جماعية، تمارين استرخاء، نشرة إرشادية",
        attachments: "دليل المهارات.pdf",
        progress: 45,
        notes: "استجابة جيدة",
        results: "",
        status: "قيد التنفيذ",
      },
      {
        id: "p5",
        name: "تنمية الدافعية للتعلم",
        icon: "Rocket",
        goal: "رفع دافعية الطالبات نحو التحصيل الدراسي",
        targetGroup: "الطالبات ذوات التحصيل المنخفض",
        date: "2026-10-05",
        duration: "شهر",
        beneficiaries: 42,
        place: "قاعة النشاط",
        owner: "المرشدة الطلابية",
        description: "برنامج تحفيزي يشمل أهدافًا أسبوعية ومتابعة فردية وحوافز.",
        activities: "لوحة الإنجاز، جلسات تحفيزية، تكريم المتميزات",
        attachments: "",
        progress: 70,
        notes: "تحسن ملحوظ في ٢٨ حالة",
        results: "ارتفاع متوسط الدرجات بنسبة ١٢٪",
        status: "قيد التنفيذ",
      },
      {
        id: "p6",
        name: "السلوك الإيجابي",
        icon: "Smile",
        goal: "تعزيز السلوكيات الإيجابية والحد من المخالفات",
        targetGroup: "جميع الطالبات",
        date: "2026-09-21",
        duration: "فصل دراسي",
        beneficiaries: 310,
        place: "المدرسة",
        owner: "لجنة التوجيه الطلابي",
        description: "نظام نقاط للسلوك الإيجابي مع تكريم أسبوعي.",
        activities: "نظام النقاط، التكريم الأسبوعي، نشرات",
        attachments: "",
        progress: 55,
        notes: "",
        results: "",
        status: "قيد التنفيذ",
      },
      {
        id: "p7",
        name: "الانضباط المدرسي",
        icon: "ShieldCheck",
        goal: "خفض نسب الغياب والتأخر الصباحي",
        targetGroup: "كثيرات الغياب والتأخر",
        date: "2026-09-28",
        duration: "فصل دراسي",
        beneficiaries: 64,
        place: "المدرسة",
        owner: "المرشدة الطلابية ووكيلة شؤون الطالبات",
        description: "متابعة يومية للحضور وتواصل مع أولياء الأمور.",
        activities: "رصد يومي، اتصال بأولياء الأمور، تعهدات",
        attachments: "كشف الغياب.xlsx",
        progress: 80,
        notes: "انخفاض التأخر بنسبة ٣٠٪",
        results: "تحسن ملحوظ في الانضباط الصباحي",
        status: "منفذ",
      },
      {
        id: "p8",
        name: "الاستخدام الآمن للإنترنت",
        icon: "Globe",
        goal: "توعية الطالبات بمخاطر الإنترنت وحمايتهن رقميًا",
        targetGroup: "جميع الطالبات",
        date: "2026-11-16",
        duration: "أسبوعان",
        beneficiaries: 310,
        place: "قاعة النشاط",
        owner: "المرشدة الطلابية",
        description: "ورش توعوية بالأمن السيبراني والابتزاز الإلكتروني.",
        activities: "ورشة، نشرة، مسابقة إلكترونية",
        attachments: "",
        progress: 10,
        notes: "",
        results: "",
        status: "مخطط",
      },
      {
        id: "p9",
        name: "دعم الحالات الخاصة",
        icon: "LifeBuoy",
        goal: "تقديم دعم نفسي واجتماعي للحالات ذات الظروف الخاصة",
        targetGroup: "الأيتام وذوات الظروف الخاصة",
        date: "2026-10-01",
        duration: "مستمر",
        beneficiaries: 23,
        place: "غرفة التوجيه",
        owner: "المرشدة الطلابية",
        description: "متابعة فردية وتنسيق دعم مادي ومعنوي بالتعاون مع الجهات المختصة.",
        activities: "جلسات فردية، تنسيق مع جمعيات، زيارات أسرية",
        attachments: "",
        progress: 65,
        notes: "سرية تامة للحالات",
        results: "",
        status: "قيد التنفيذ",
      },
    ],
    students: [],
    services: [
      {
        id: "sv1",
        type: "مجلس أولياء الأمور",
        date: "2026-09-24",
        time: "10:00",
        place: "قاعة الاجتماعات",
        targetGroup: "أولياء أمور الطالبات",
        beneficiaries: 45,
        subject: "خطة التوجيه الطلابي للفصل الأول",
        goal: "إشراك الأسرة في متابعة الطالبات",
        actions: "عرض الخطة، مناقشة الملاحظات، توزيع نشرة",
        recommendations: "تفعيل قناة تواصل دورية مع الأسر",
        notes: "حضور جيد",
        attachments: "محضر الاجتماع.pdf",
        owner: "المرشدة الطلابية",
        status: "منفذ",
      },
      {
        id: "sv2",
        type: "جلسة فردية",
        date: "2026-09-22",
        time: "09:15",
        place: "غرفة التوجيه",
        targetGroup: "طالبة",
        beneficiaries: 1,
        subject: "قلق الاختبارات",
        goal: "خفض مستوى القلق وتحسين الاستعداد",
        actions: "تمارين تنفس، جدول مذاكرة",
        recommendations: "متابعة بعد أسبوعين",
        notes: "سرية",
        attachments: "",
        owner: "المرشدة الطلابية",
        status: "منفذ",
      },
      {
        id: "sv3",
        type: "إرشاد جمعي",
        date: "2026-10-01",
        time: "11:00",
        place: "قاعة النشاط",
        targetGroup: "طالبات الثالث المتوسط",
        beneficiaries: 60,
        subject: "مهارات التخطيط للمستقبل",
        goal: "تنمية وعي الطالبات بالتخطيط الدراسي",
        actions: "عرض تفاعلي، تمارين جماعية",
        recommendations: "",
        notes: "",
        attachments: "",
        owner: "المرشدة الطلابية",
        status: "مجدول",
      },
      {
        id: "sv4",
        type: "اجتماع اللجنة",
        date: "2026-09-17",
        time: "12:30",
        place: "غرفة المعلمات",
        targetGroup: "لجنة التوجيه الطلابي",
        beneficiaries: 8,
        subject: "مناقشة الحالات المحولة",
        goal: "اتخاذ قرارات بشأن الحالات",
        actions: "دراسة ٦ حالات، توزيع مهام المتابعة",
        recommendations: "متابعة أسبوعية للحالات المرتفعة",
        notes: "",
        attachments: "",
        owner: "لجنة التوجيه",
        status: "منفذ",
      },
      {
        id: "sv5",
        type: "جلسة جمعية",
        date: "2026-10-06",
        time: "10:30",
        place: "غرفة التوجيه",
        targetGroup: "مجموعة من ٨ طالبات",
        beneficiaries: 8,
        subject: "إدارة الوقت",
        goal: "تنظيم وقت المذاكرة",
        actions: "",
        recommendations: "",
        notes: "",
        attachments: "",
        owner: "المرشدة الطلابية",
        status: "مجدول",
      },
      {
        id: "sv6",
        type: "اجتماع المجلس الطلابي",
        date: "2026-09-29",
        time: "11:30",
        place: "قاعة النشاط",
        targetGroup: "عضوات المجلس الطلابي",
        beneficiaries: 15,
        subject: "خطة الأنشطة الطلابية",
        goal: "إشراك الطالبات في التخطيط",
        actions: "",
        recommendations: "",
        notes: "",
        attachments: "",
        owner: "رائدة النشاط",
        status: "مجدول",
      },
      {
        id: "sv7",
        type: "المواقف الطارئة",
        date: "2026-09-19",
        time: "08:40",
        place: "الفناء",
        targetGroup: "طالبتان",
        beneficiaries: 2,
        subject: "خلاف بين طالبتين",
        goal: "احتواء الموقف وإصلاح ذات البين",
        actions: "جلسة صلح، تعهد سلوكي",
        recommendations: "متابعة سلوكية لمدة شهر",
        notes: "",
        attachments: "",
        owner: "المرشدة الطلابية",
        status: "منفذ",
      },
    ],
    termPlan: [
      {
        id: "tp1",
        term: "الفصل الدراسي الأول",
        generalGoal: "تهيئة بيئة مدرسية آمنة ومحفزة للطالبات",
        detailedGoals: "تهيئة المستجدات، خفض الغياب، رفع الدافعية",
        program: "التهيئة والإرشاد",
        activities: "لقاء تعريفي، جولة مدرسية، نشرة",
        targetGroup: "طالبات الأول المتوسط",
        owner: "المرشدة الطلابية",
        date: "2026-09-07",
        indicators: "نسبة رضا المستجدات ٩٠٪",
        progress: 100,
        results: "تحقق الهدف بالكامل",
        recommendations: "تكرار البرنامج سنويًا",
      },
      {
        id: "tp2",
        term: "الفصل الدراسي الأول",
        generalGoal: "خفض نسب الغياب والتأخر",
        detailedGoals: "متابعة يومية، تواصل أسري، حوافز الانضباط",
        program: "الانضباط المدرسي",
        activities: "رصد يومي، اتصالات، تعهدات",
        targetGroup: "كثيرات الغياب والتأخر",
        owner: "المرشدة ووكيلة شؤون الطالبات",
        date: "2026-09-28",
        indicators: "خفض الغياب بنسبة ٢٥٪",
        progress: 80,
        results: "انخفاض ملحوظ",
        recommendations: "الاستمرار في المتابعة اليومية",
      },
      {
        id: "tp3",
        term: "الفصل الدراسي الأول",
        generalGoal: "رفع الوعي المهني لدى الطالبات",
        detailedGoals: "تعريف بالمسارات، مقاييس ميول",
        program: "التوجيه المهني",
        activities: "ورش، مقياس ميول، لقاءات",
        targetGroup: "طالبات الثالث المتوسط",
        owner: "المرشدة الطلابية",
        date: "2026-10-12",
        indicators: "مشاركة ٨٠٪ من الطالبات",
        progress: 60,
        results: "",
        recommendations: "",
      },
      {
        id: "tp4",
        term: "الفصل الدراسي الثاني",
        generalGoal: "تعزيز الصحة النفسية للطالبات",
        detailedGoals: "جلسات مهارات، ورش أسرية",
        program: "المهارات النفسية",
        activities: "جلسات، نشرات، ورش",
        targetGroup: "جميع الطالبات",
        owner: "المرشدة الطلابية",
        date: "2027-01-18",
        indicators: "تنفيذ ٨ جلسات",
        progress: 15,
        results: "",
        recommendations: "",
      },
    ],
    weeklyPlan: [
      {
        id: "w1",
        week: "الأسبوع الرابع",
        day: "الأحد",
        date: "2026-09-20",
        activity: "جلسة فردية - قلق الاختبارات",
        goal: "خفض القلق",
        targetGroup: "طالبة",
        time: "09:15",
        owner: "المرشدة الطلابية",
        done: true,
        notes: "",
      },
      {
        id: "w2",
        week: "الأسبوع الرابع",
        day: "الاثنين",
        date: "2026-09-21",
        activity: "متابعة كشوف الغياب",
        goal: "رصد المتغيبات",
        targetGroup: "جميع الصفوف",
        time: "07:30",
        owner: "المرشدة الطلابية",
        done: true,
        notes: "٦ حالات جديدة",
      },
      {
        id: "w3",
        week: "الأسبوع الرابع",
        day: "الثلاثاء",
        date: "2026-09-22",
        activity: "ورشة السلوك الإيجابي",
        goal: "تعزيز السلوك",
        targetGroup: "الثاني المتوسط",
        time: "10:00",
        owner: "لجنة التوجيه",
        done: true,
        notes: "",
      },
      {
        id: "w4",
        week: "الأسبوع الرابع",
        day: "الأربعاء",
        date: "2026-09-23",
        activity: "لقاء أولياء الأمور",
        goal: "إشراك الأسرة",
        targetGroup: "أولياء الأمور",
        time: "10:00",
        owner: "المرشدة الطلابية",
        done: false,
        notes: "تحضير العرض",
      },
      {
        id: "w5",
        week: "الأسبوع الرابع",
        day: "الخميس",
        date: "2026-09-24",
        activity: "إذاعة مدرسية عن رفق",
        goal: "نشر ثقافة الرفق",
        targetGroup: "جميع الطالبات",
        time: "07:15",
        owner: "رائدة النشاط",
        done: false,
        notes: "",
      },
      {
        id: "w6",
        week: "الأسبوع الخامس",
        day: "الأحد",
        date: "2026-09-27",
        activity: "متابعة حالات الغياب المرتفع",
        goal: "خفض الغياب",
        targetGroup: "٦ طالبات",
        time: "08:00",
        owner: "المرشدة الطلابية",
        done: false,
        notes: "",
      },
      {
        id: "w7",
        week: "الأسبوع الخامس",
        day: "الثلاثاء",
        date: "2026-09-29",
        activity: "اجتماع المجلس الطلابي",
        goal: "خطة الأنشطة",
        targetGroup: "عضوات المجلس",
        time: "11:30",
        owner: "رائدة النشاط",
        done: false,
        notes: "",
      },
      {
        id: "w8",
        week: "الأسبوع الخامس",
        day: "الخميس",
        date: "2026-10-01",
        activity: "إرشاد جمعي - التخطيط للمستقبل",
        goal: "وعي مهني",
        targetGroup: "الثالث المتوسط",
        time: "11:00",
        owner: "المرشدة الطلابية",
        done: false,
        notes: "",
      },
    ],
    settings: {
      schoolName: "المتوسطة الثانية عشرة",
      logoUrl: "",
      academicYear: "١٤٤٧ هـ",
      term: "الفصل الدراسي الأول",
      notifyAppointments: true,
      notifyFollowUps: true,
      notifyTasks: true,
    },
    users: [
      { id: "u1", name: "أ. نورة القحطاني", role: "مرشدة طلابية", email: "noura@moe.edu.sa", active: true },
      { id: "u2", name: "أ. هند العمري", role: "مديرة", email: "hind@moe.edu.sa", active: true },
      { id: "u3", name: "أ. عبير الشهري", role: "مشرفة", email: "abeer@moe.edu.sa", active: false },
    ],
    activities: [
      { id: "a1", date: "2026-09-22", text: "تم تسجيل جلسة فردية جديدة (قلق الاختبارات)" },
      { id: "a2", date: "2026-09-21", text: "تحديث كشف الغياب ورصد ٦ حالات جديدة" },
      { id: "a3", date: "2026-09-20", text: "إضافة طالبة جديدة إلى تصنيف الضعيفات" },
      { id: "a4", date: "2026-09-17", text: "اجتماع لجنة التوجيه الطلابي ومناقشة ٦ حالات" },
    ],
  };
}
