/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CounselorRouteImport } from './routes/counselor'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgramsIdRouteImport } from './routes/programs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselorRoute = CounselorRouteImport.update({
  id: '/counselor',
  path: '/counselor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counselor': typeof CounselorRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/programs/$id': typeof ProgramsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counselor': typeof CounselorRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/programs/$id': typeof ProgramsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counselor': typeof CounselorRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/programs/$id': typeof ProgramsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counselor' | '/programs' | '/programs/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counselor' | '/programs' | '/programs/$id'
  id: '__root__' | '/' | '/counselor' | '/programs' | '/programs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounselorRoute: typeof CounselorRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselor': {
      id: '/counselor'
      path: '/counselor'
      fullPath: '/counselor'
      preLoaderRoute: typeof CounselorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsIdRoute: typeof ProgramsIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsIdRoute: ProgramsIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounselorRoute: CounselorRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
